#include "PracticalWork/1.h"

#include "PracticalWork/3.h"
#include "PracticalWork/4.h"
#include "PracticalWork/5.h"
#include "PracticalWork/6.h"
#include "PracticalWork/7.h"
#include "PracticalWork/8.h"
#include "PracticalWork/9.h"
#include "PracticalWork/10.h"
#include "PracticalWork/11.h"
#include "PracticalWork/12.h"